
IF OBJECT_ID('brozen.erp_CUST_AZ12','U') IS NOT NULL
	DROP TABLE brozen.erp_CUST_AZ12
CREATE TABLE brozen.erp_CUST_AZ12(
CID NVARCHAR(40),
BDATE DATE,
GEN NVARCHAR(50)
)


--erp_LOC_A101
IF OBJECT_ID('brozen.erp_LOC_A101','U') IS NOT NULL
	DROP TABLE brozen.erp_LOC_A101
CREATE TABLE brozen.erp_LOC_A101(
CID NVARCHAR(40),
CNTRY NVARCHAR(40)
)


--erp_LOC_
IF OBJECT_ID('brozen.erp_PX_CAT_G1V2','U') IS NOT NULL
	DROP TABLE brozen.erp_PX_CAT_G1V2
CREATE TABLE brozen.erp_PX_CAT_G1V2(
ID NVARCHAR(40),
CAT NVARCHAR(40),
SUBCATE NVARCHAR(34),
MAINTENANCE NVARCHAR(34)
)




