--clean the erp_cust_az12 table and insert into silver layer.
INSERT INTO silver.erp_CUST_AZ12(
CID,
BDATE,
GEN)

SELECT
CASE WHEN CID LIKE 'NAS%' THEN SUBSTRING(CID,4,LEN(CID))
	ELSE CID
END AS CID,
CASE WHEN BDATE  >GETDATE() THEN NULL
	ELSE BDATE
END AS BDATE,
CASE WHEN UPPER(TRIM(GEN)) IN ('F','FEMALE') THEN 'FEMALE'
	 WHEN UPPER(TRIM(GEN)) IN ('M','MALE') THEN 'MALE'
	 ELSE 'N/A'
END AS GEN
FROM brozen.erp_CUST_AZ12